version: '3.8'

services:
  dev-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: ryd3v/dev-container:latest
    container_name: dev-box
    environment:
      - TERM=xterm
    volumes:
      - ./src:/home/ryd3v/src
    tty: true
